# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-26 02:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='users',
        ),
    ]
